-- Bestehende Tabellen löschen (Reihenfolge wegen FK beachten)
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

-- Authors-Tabelle mit ID als Auto-Increment (IDENTITY)
CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    age INTEGER
);

-- Books-Tabelle mit FK auf authors.id
CREATE TABLE books (
    isbn TEXT NOT NULL PRIMARY KEY,
    title TEXT,
    author_id BIGINT,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES authors(id)
);
